# Generated by Django 5.2.7 on 2025-12-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_tag_notetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
